// Generated by ts-to-zod
import { z } from "zod";

export const pixelSchema = z.object({
  id: z.string(),
  color: z.string(),
  version: z.number(),
  gridId: z.string(),
});

export const gridSchema = z.object({
  pixels: z.array(pixelSchema),
});

export const parttialGridSchema = z.object({
  pixels: z.array(pixelSchema.partial()),
});

export const arrayOfGridsSchema = z.array(parttialGridSchema);
