import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { GridRender } from "../components/GridRender/GridRender";
import { GridEditor } from "../components/GridEditor";
import { getAllGrids } from "../server/service/gridFunctions";
import { Grid, Pixel } from "@prisma/client";

export async function getServerSideProps(context) {
  const allGrids = await getAllGrids();
  return { props: allGrids }; // will be passed to the page component as props
}

const Home: NextPage<
  {
    grids: (Grid & {
      pixels: Pixel[];
    })[];
  },
  {}
> = (props) => {
  const hello = trpc.proxy.example.hello.useQuery({ text: "from tRPC" });
  // const mutation = trpc.proxy.grid.makeManyGrids.useMutation();
  // const deleteAll = trpc.proxy.grid.deleteAll.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        <GridRender grids={props.grids || []} />
        {/* <button onClick={() => mutation.mutate()}>Mutation</button>
        <button onClick={() => deleteAll.mutate()}>Clear All</button> */}
        <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <h2>Edit this grid</h2>
        <GridEditor />
      </main>
    </>
  );
};

export default Home;
