import type { NextPage } from "next";
import Head from "next/head";
import { useForm, SubmitHandler } from "react-hook-form";
import { trpc } from "../../utils/trpc";

type Inputs = {
  gridId: string;
};

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>();
  const deleteGrid = trpc.proxy.grid.deleteGrid.useMutation();

  const onSubmit: SubmitHandler<Inputs> = (data) => {
    console.log(data);
    deleteGrid.mutate({ gridId: data.gridId });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        <h1>Admin</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label htmlFor="gridId">Delete a Grid</label>
          <input
            {...register("gridId", { required: true })}
            type="text"
            placeholder="gridId"
          />
          {errors.gridId && <p>This field is required</p>}
          <button type="submit">Delete</button>
        </form>
      </main>
    </>
  );
};

export default Home;
